language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: XSoZcdIphVtIpiF502M9AArjpBEaRREIZ+HF3b31fit7H56VtWON0ATJSJdPBBKY7GkoilZ59/6+4nOA3j0ILaPRB9AYCqaKgOA9xOj7NOujG7OZRSu2jHFKlklvI2+cWctjfCP185q20zEBKBudc2qtR8FftBIMdo30U6gWWC8=
  - secure: fkwNKpEpGcLQjEvIQGI52Pa74Jh9VAXN98n7w0t6UDsbJrATZOJddXQp3Z+3OUDIW+r8ICRvds5MEJ8hSUK6io3aZwWhvc3k6m25vvnQSPzZ3AImFiBefaGmKEukwkbEWuNq7fLPscYzr1wlAw3tP7xrlakFrs0+L9RtCZhMFZ8=
  - secure: Y7WRzOI51yoHftG/f9tbS2J4hYf+feAV9aUm7jpf2VaZ4KHhq1PuyFvUt3nQdV+kvE9ZMx0oejQeyNCaX6XgZrCI3oGgD4kUZeKPit22/W/cC4Yw36B/+/VQeWgJ9faoraiJN2U/PcObQQkB1euZZqvEPgReUhWCVBoNVVzjodg=
  - secure: Di+q6nl23ncQDYJZY4JvZ9BA+B1sUm8I39CQAskzvbAO1845/8HB2SohSE73w8zVVQbAziQlCUp3s+35lt47OKCxaPnCFip3q7ebVhZdKNyvgVxiChfvGqtL6cxWaRINYlta5jmg0+p3ViOHs1yB86ebxp2jb+Zz+nUjpSooKzA=
  - secure: GKYHjoztDOARiIP9/reSNJTeSfNzCqFN7Au+MgYfKBMQBMSvBf5i5mx50d/rbJLBGfauhvWtCiO68HNlhQoMthFonkwOgVHyRh1ItvDr1Q2HIv1g5qgiVszfnMRgXdiIZSVDq6E3z/4mdzcEtU02sMzoTvXBWaLPHRUObkwaQnc=
