language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: XSoZcdIphVtIpiF502M9AArjpBEaRREIZ+HF3b31fit7H56VtWON0ATJSJdPBBKY7GkoilZ59/6+4nOA3j0ILaPRB9AYCqaKgOA9xOj7NOujG7OZRSu2jHFKlklvI2+cWctjfCP185q20zEBKBudc2qtR8FftBIMdo30U6gWWC8=
  - secure: fkwNKpEpGcLQjEvIQGI52Pa74Jh9VAXN98n7w0t6UDsbJrATZOJddXQp3Z+3OUDIW+r8ICRvds5MEJ8hSUK6io3aZwWhvc3k6m25vvnQSPzZ3AImFiBefaGmKEukwkbEWuNq7fLPscYzr1wlAw3tP7xrlakFrs0+L9RtCZhMFZ8=
